-- Seed dos planos, lotes Fundador, configurações da plataforma e custos de IA
-- Idempotente: usa ON CONFLICT DO NOTHING

-- subscription_plans
INSERT INTO public.subscription_plans (tier,name,price,setup_fee,max_items,ai_generations_per_day,color,border_color,badge_color,benefits,category,is_active,is_popular,sort_order,max_photos_per_listing,storage_mb,ai_credits_per_month,monthly_visits_limit) VALUES ('basico','Básico',0,0,5,25,'from-slate-500 to-slate-700','border-slate-400','bg-slate-500 text-white','["Até 5 anúncios ativos", "Vitrine própria (sua loja online)", "URL personalizada /seu-nome", "1 Layout (Marketplace) + 1 Tema", "Painel do vendedor completo", "Estatísticas básicas", "Gerador de contratos (1 modelo)", "QR Code dos anúncios e propostas PDF", "Calculadora de Lucro (ROI)", "Sistema de Parcerias entre corretores", "Push: 1 envio por dia"]'::jsonb,'corretor',true,false,0,5,15,25,3000) ON CONFLICT (tier) DO NOTHING;
INSERT INTO public.subscription_plans (tier,name,price,setup_fee,max_items,ai_generations_per_day,color,border_color,badge_color,benefits,category,is_active,is_popular,sort_order,max_photos_per_listing,storage_mb,ai_credits_per_month,monthly_visits_limit) VALUES ('start','Start',29.90,0,30,250,'from-emerald-500 to-teal-700','border-emerald-400','bg-emerald-500 text-white','["Até 30 anúncios ativos", "Vitrine Lvl 1 — mais visibilidade", "1 Layout (Showcase) + 3 Temas", "URL personalizada /seu-nome", "Painel do vendedor completo", "CRM Kanban completo", "Stories (estilo Instagram)", "Página de Captação de imóveis", "Todos os modelos de contrato", "Simulador de Financiamento", "PDF de Proposta profissional", "QR Code dos anúncios", "Calculadora de Lucro (ROI)", "Sistema de Parcerias entre corretores", "Estatísticas básicas", "Selo Start + Hero Banner", "Destaque na listagem", "Push: 1 envio por dia"]'::jsonb,'corretor',true,false,1,5,75,250,30000) ON CONFLICT (tier) DO NOTHING;
INSERT INTO public.subscription_plans (tier,name,price,setup_fee,max_items,ai_generations_per_day,color,border_color,badge_color,benefits,category,is_active,is_popular,sort_order,max_photos_per_listing,storage_mb,ai_credits_per_month,monthly_visits_limit) VALUES ('premium','Premium',59.90,0,75,600,'from-amber-500 to-orange-600','border-amber-400','bg-amber-500 text-white','["Até 75 anúncios ativos", "Até 10 fotos por anúncio", "Vitrine Lvl 2 — destaque superior", "4 Layouts + 6 Temas", "URL personalizada /seu-nome", "Painel do vendedor completo", "CRM Kanban completo", "Stories (estilo Instagram)", "Bot de Captação (fluxo fixo)", "Página de Captação de imóveis", "Todos os modelos de contrato", "Simulador de Financiamento", "PDF de Proposta profissional", "Calculadora de Lucro (ROI)", "Sistema de Parcerias entre corretores", "Vídeo banner hero (autoplay)", "Modo Cinema imersivo", "Efeitos visuais na loja", "Gestão de Aluguéis completa", "Sistema de ADS integrado", "Estatísticas avançadas", "Selo Premium nos anúncios", "Hero Banner", "Push Notifications: 2 envios por dia", "Suporte prioritário"]'::jsonb,'corretor',true,true,2,10,380,600,80000) ON CONFLICT (tier) DO NOTHING;
INSERT INTO public.subscription_plans (tier,name,price,setup_fee,max_items,ai_generations_per_day,color,border_color,badge_color,benefits,category,is_active,is_popular,sort_order,max_photos_per_listing,storage_mb,ai_credits_per_month,monthly_visits_limit) VALUES ('prime','Prime',119.90,0,150,1000,'from-fuchsia-500 to-purple-700','border-fuchsia-400','bg-fuchsia-500 text-white','["Até 150 anúncios ativos", "Até 20 fotos por anúncio", "Vitrine Lvl 3 — máximo individual", "Todos os 7 Layouts + Temas", "URL personalizada /seu-nome", "Painel do vendedor completo", "CRM Kanban completo", "Stories (estilo Instagram)", "Bot de Captação com IA Inteligente", "Página de Captação de imóveis", "Todos os modelos de contrato", "Simulador de Financiamento", "PDF de Proposta profissional", "Calculadora de Lucro (ROI)", "Sistema de Parcerias entre corretores", "Vídeo banner hero (autoplay)", "Modo Cinema imersivo", "Efeitos visuais na loja", "Gestão de Aluguéis completa", "Sistema de ADS integrado", "Instagram na loja", "SEO otimizado (cidade/bairro)", "Destaque Épico (até 5 imóveis)", "Galeria Showroom + Copywriting", "Estatísticas avançadas", "Selo Premium exclusivo", "Hero Banner", "Push Notifications: 3 envios por dia", "Suporte VIP dedicado"]'::jsonb,'corretor',true,false,3,20,1500,1500,200000) ON CONFLICT (tier) DO NOTHING;
INSERT INTO public.subscription_plans (tier,name,price,setup_fee,max_items,ai_generations_per_day,color,border_color,badge_color,benefits,category,is_active,is_popular,sort_order,max_photos_per_listing,storage_mb,ai_credits_per_month,monthly_visits_limit) VALUES ('imob_basico','Imob Grátis',0,0,3,25,'from-slate-500 to-blue-700','border-slate-400','bg-slate-500 text-white','["Até 3 imóveis ativos", "Até 1 corretor na equipe", "25 créditos de IA por mês", "Vitrine padrão (Marketplace)", "Catálogo público responsivo", "Compartilhamento WhatsApp", "Suporte por e-mail"]'::jsonb,'imobiliaria',true,false,9,5,15,25,3000) ON CONFLICT (tier) DO NOTHING;
INSERT INTO public.subscription_plans (tier,name,price,setup_fee,max_items,ai_generations_per_day,color,border_color,badge_color,benefits,category,is_active,is_popular,sort_order,max_photos_per_listing,storage_mb,ai_credits_per_month,monthly_visits_limit) VALUES ('imob_start','Imob Start',119.90,0,100,1500,'from-cyan-500 to-blue-700','border-cyan-400','bg-cyan-500 text-white','["Até 100 imóveis ativos", "Até 5 corretores na equipe", "1.500 créditos de IA por mês", "Lojas espelho para cada corretor", "CRM completo com kanban", "Todos os layouts de loja", "Marca d''água personalizada", "Stories de imóveis", "Suporte WhatsApp"]'::jsonb,'imobiliaria',true,false,10,15,750,1500,200000) ON CONFLICT (tier) DO NOTHING;
INSERT INTO public.subscription_plans (tier,name,price,setup_fee,max_items,ai_generations_per_day,color,border_color,badge_color,benefits,category,is_active,is_popular,sort_order,max_photos_per_listing,storage_mb,ai_credits_per_month,monthly_visits_limit) VALUES ('imob_pro','Imob Pro',239.90,0,300,3000,'from-violet-500 to-indigo-700','border-violet-400','bg-violet-500 text-white','["Até 300 imóveis ativos", "Até 15 corretores na equipe", "3.000 créditos de IA por mês", "Página SEO para cada corretor", "Bot de captação com IA", "Bot de agendamento", "Domínio personalizado", "Selo de imobiliária verificada", "Tags coloridas em destaque", "CRM avançado + automações", "Gerente de conta dedicado", "Suporte prioritário"]'::jsonb,'imobiliaria',true,true,11,20,3000,3000,500000) ON CONFLICT (tier) DO NOTHING;
INSERT INTO public.subscription_plans (tier,name,price,setup_fee,max_items,ai_generations_per_day,color,border_color,badge_color,benefits,category,is_active,is_popular,sort_order,max_photos_per_listing,storage_mb,ai_credits_per_month,monthly_visits_limit) VALUES ('imob_elite','Imob Elite',479.90,0,5000,6000,'from-fuchsia-500 to-purple-700','border-fuchsia-400','bg-fuchsia-500 text-white','["Imóveis ilimitados", "Corretores ilimitados", "6.000 créditos de IA por mês", "Selo Elite exclusivo", "Topo absoluto da vitrine", "Páginas cinematográficas", "Múltiplos domínios", "Vídeos no hero da loja", "Análise de leads por IA", "Consultor estratégico exclusivo", "Suporte 24/7 prioridade máxima"]'::jsonb,'imobiliaria',true,false,12,25,12000,6000,1500000) ON CONFLICT (tier) DO NOTHING;
INSERT INTO public.subscription_plans (tier,name,price,setup_fee,max_items,ai_generations_per_day,color,border_color,badge_color,benefits,category,is_active,is_popular,sort_order,max_photos_per_listing,storage_mb,ai_credits_per_month,monthly_visits_limit) VALUES ('const_basico','Construtora Grátis',0,0,3,25,'from-slate-500 to-zinc-700','border-slate-400','bg-slate-500 text-white','["Até 3 unidades cadastradas", "Até 1 vendedor na equipe", "25 créditos de IA por mês", "Vitrine padrão (Marketplace)", "Catálogo público responsivo", "Compartilhamento WhatsApp", "Suporte por e-mail"]'::jsonb,'construtora',true,false,19,5,15,25,3000) ON CONFLICT (tier) DO NOTHING;
INSERT INTO public.subscription_plans (tier,name,price,setup_fee,max_items,ai_generations_per_day,color,border_color,badge_color,benefits,category,is_active,is_popular,sort_order,max_photos_per_listing,storage_mb,ai_credits_per_month,monthly_visits_limit) VALUES ('const_start','Construtora Start',179.90,0,150,2000,'from-cyan-500 to-blue-700','border-cyan-400','bg-cyan-500 text-white','["Até 150 unidades cadastradas", "Até 10 vendedores na equipe", "2.000 créditos de IA por mês", "Páginas de empreendimento", "Plantas e tabela de preços", "Bot de captação para lançamentos", "CRM com pipeline de vendas", "Suporte WhatsApp"]'::jsonb,'construtora',true,false,20,20,1500,2000,300000) ON CONFLICT (tier) DO NOTHING;
INSERT INTO public.subscription_plans (tier,name,price,setup_fee,max_items,ai_generations_per_day,color,border_color,badge_color,benefits,category,is_active,is_popular,sort_order,max_photos_per_listing,storage_mb,ai_credits_per_month,monthly_visits_limit) VALUES ('const_pro','Construtora Pro',359.90,0,500,4500,'from-violet-500 to-indigo-700','border-violet-400','bg-violet-500 text-white','["Até 500 unidades cadastradas", "Até 30 vendedores na equipe", "4.500 créditos de IA por mês", "Múltiplos empreendimentos em destaque", "Páginas cinematográficas por imóvel", "Tour virtual integrado", "Bot de captação + agendamento", "Domínio personalizado", "Selo Construtora Verificada", "Gerente de conta dedicado", "Suporte prioritário"]'::jsonb,'construtora',true,true,21,25,6000,4500,800000) ON CONFLICT (tier) DO NOTHING;
INSERT INTO public.subscription_plans (tier,name,price,setup_fee,max_items,ai_generations_per_day,color,border_color,badge_color,benefits,category,is_active,is_popular,sort_order,max_photos_per_listing,storage_mb,ai_credits_per_month,monthly_visits_limit) VALUES ('const_master','Construtora Master',779.90,0,10000,10000,'from-amber-500 to-orange-600','border-yellow-500','bg-yellow-500 text-white','["Unidades ilimitadas", "Vendedores ilimitados", "10.000 créditos de IA por mês", "Selo Master da construtora", "Topo absoluto da vitrine de lançamentos", "Página cinematográfica por empreendimento", "Vídeos no hero", "Análise de leads por IA", "Integração com portais externos", "Consultor estratégico exclusivo", "Onboarding personalizado", "SLA garantido + suporte 24/7"]'::jsonb,'construtora',true,false,22,30,25000,10000,3000000) ON CONFLICT (tier) DO NOTHING;
INSERT INTO public.subscription_plans (tier,name,price,setup_fee,max_items,ai_generations_per_day,color,border_color,badge_color,benefits,category,is_active,is_popular,sort_order,max_photos_per_listing,storage_mb,ai_credits_per_month,monthly_visits_limit) VALUES ('fundador_corretor','Fundador',97,0,75,0,'from-slate-500 to-slate-600','border-slate-400','bg-slate-500 text-white','["Pagamento único — válido por 12 meses", "Equivalente ao plano VIP/Premium", "500 créditos IA bônus (única vez)", "Todos os benefícios do Premium incluídos", "Selo Fundador exclusivo", "Lote limitado por preço promocional"]'::jsonb,'fundador',true,false,90,10,380,600,80000) ON CONFLICT (tier) DO NOTHING;
INSERT INTO public.subscription_plans (tier,name,price,setup_fee,max_items,ai_generations_per_day,color,border_color,badge_color,benefits,category,is_active,is_popular,sort_order,max_photos_per_listing,storage_mb,ai_credits_per_month,monthly_visits_limit) VALUES ('fundador_empresa','Fundador Empresa',97,0,9999,0,'from-slate-500 to-slate-600','border-slate-400','bg-slate-500 text-white','["Pagamento único — válido por 12 meses", "Equivalente ao plano Black Empresa", "1750 créditos IA bônus (única vez)", "Todos os benefícios do Black incluídos", "Selo Fundador Empresa exclusivo", "Lote limitado por preço promocional"]'::jsonb,'fundador',true,false,91,30,30000,12000,3000000) ON CONFLICT (tier) DO NOTHING;

-- founder_lots
INSERT INTO public.founder_lots (category,lot_number,price,total_slots,used_slots,is_active,inherited_tier,ia_credits,monthly_price,ia_credits_monthly) VALUES ('construtora',1,4679.40,500,0,true,'const_master',60000,389.95,5000) ON CONFLICT (category, lot_number) DO NOTHING;
INSERT INTO public.founder_lots (category,lot_number,price,total_slots,used_slots,is_active,inherited_tier,ia_credits,monthly_price,ia_credits_monthly) VALUES ('corretor',1,719.40,500,0,true,'prime',9000,59.95,750) ON CONFLICT (category, lot_number) DO NOTHING;
INSERT INTO public.founder_lots (category,lot_number,price,total_slots,used_slots,is_active,inherited_tier,ia_credits,monthly_price,ia_credits_monthly) VALUES ('empresa',1,2879.40,500,0,true,'imob_elite',36000,239.95,3000) ON CONFLICT (category, lot_number) DO NOTHING;

-- founder_settings (singleton id=1)
INSERT INTO public.founder_settings (id, is_enabled, loop_enabled, price_increment, default_slots) VALUES (1, true, true, 30, 500) ON CONFLICT (id) DO NOTHING;

-- platform_settings
INSERT INTO public.platform_settings (key,value) VALUES ('admin_push_seller_id','b9a519ce-31ad-4e76-8666-84acd357ad56') ON CONFLICT (key) DO NOTHING;
INSERT INTO public.platform_settings (key,value) VALUES ('homepage_theme','espirito-santo') ON CONFLICT (key) DO NOTHING;
INSERT INTO public.platform_settings (key,value) VALUES ('login_hero_image','preset-07') ON CONFLICT (key) DO NOTHING;
INSERT INTO public.platform_settings (key,value) VALUES ('homepage_mode','marketplace') ON CONFLICT (key) DO NOTHING;

-- ai_tool_costs
INSERT INTO public.ai_tool_costs (tool_key,label,cost,description,category,is_session_based,session_window_minutes) VALUES ('credit_purchase','Compra de Créditos Avulsos',0,'Registro de compra de créditos extras','sistema',false,0) ON CONFLICT (tool_key) DO NOTHING;
INSERT INTO public.ai_tool_costs (tool_key,label,cost,description,category,is_session_based,session_window_minutes) VALUES ('founder_lot_grant','Concessão de Lote Fundador',0,'Registro de créditos concedidos pelo plano Fundador','sistema',false,0) ON CONFLICT (tool_key) DO NOTHING;
INSERT INTO public.ai_tool_costs (tool_key,label,cost,description,category,is_session_based,session_window_minutes) VALUES ('platform_help_chat','Ajuda da Plataforma (IA)',1,'Suporte interno via chat IA','bot',true,30) ON CONFLICT (tool_key) DO NOTHING;
INSERT INTO public.ai_tool_costs (tool_key,label,cost,description,category,is_session_based,session_window_minutes) VALUES ('gallery_ai_headline','Manchete da Galeria (IA)',1,'Gera título cinematográfico para o showroom','texto',false,0) ON CONFLICT (tool_key) DO NOTHING;
INSERT INTO public.ai_tool_costs (tool_key,label,cost,description,category,is_session_based,session_window_minutes) VALUES ('capture_bot_chat','Bot de Captação (Chat)',3,'Conversa com lead via bot de captação','bot',true,30) ON CONFLICT (tool_key) DO NOTHING;
INSERT INTO public.ai_tool_costs (tool_key,label,cost,description,category,is_session_based,session_window_minutes) VALUES ('agenda_bot_chat','Bot de Agendamento (Chat)',3,'Conversa com cliente para agendar visita','bot',true,30) ON CONFLICT (tool_key) DO NOTHING;
INSERT INTO public.ai_tool_costs (tool_key,label,cost,description,category,is_session_based,session_window_minutes) VALUES ('invite_chat','Chat de Convite (IA)',2,'Atendimento via página de convite','bot',true,30) ON CONFLICT (tool_key) DO NOTHING;
INSERT INTO public.ai_tool_costs (tool_key,label,cost,description,category,is_session_based,session_window_minutes) VALUES ('capture_ad_copy','Copywriter de Anúncio (IA)',2,'Gera descrição persuasiva para o imóvel','texto',false,0) ON CONFLICT (tool_key) DO NOTHING;
INSERT INTO public.ai_tool_costs (tool_key,label,cost,description,category,is_session_based,session_window_minutes) VALUES ('valuation_ad','Anúncio de Avaliação (IA)',3,'Gera anúncio para serviço de avaliação','texto',false,0) ON CONFLICT (tool_key) DO NOTHING;
INSERT INTO public.ai_tool_costs (tool_key,label,cost,description,category,is_session_based,session_window_minutes) VALUES ('contract_generation','Gerador de Contrato (IA)',4,'Gera minuta de contrato personalizada','texto',false,0) ON CONFLICT (tool_key) DO NOTHING;
INSERT INTO public.ai_tool_costs (tool_key,label,cost,description,category,is_session_based,session_window_minutes) VALUES ('photo_analysis','Análise de Fotos do Imóvel (IA)',5,'Analisa qualidade e sugere melhorias nas fotos','visao',false,0) ON CONFLICT (tool_key) DO NOTHING;
INSERT INTO public.ai_tool_costs (tool_key,label,cost,description,category,is_session_based,session_window_minutes) VALUES ('property_valuation','Avaliação de Imóvel (IA)',6,'Avaliação completa com análise visual e de mercado','visao',false,0) ON CONFLICT (tool_key) DO NOTHING;