ALTER TABLE public.property_valuations
  ADD COLUMN IF NOT EXISTS inputs jsonb DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS area_coberta_externa numeric,
  ADD COLUMN IF NOT EXISTS area_util numeric,
  ADD COLUMN IF NOT EXISTS lavabos integer,
  ADD COLUMN IF NOT EXISTS sala_estar boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS sala_jantar boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS sala_tv boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS copa boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS lavanderia boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS area_servico boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS closet boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS despensa boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS varanda_interna boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS regiao_valorizada boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS rua_tranquila boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS proximo_comercio boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS proximo_escola boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS proximo_hospital boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS vista_privilegiada boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS area_risco boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS piso_qualidade text,
  ADD COLUMN IF NOT EXISTS banheiro_qualidade text,
  ADD COLUMN IF NOT EXISTS cozinha_qualidade text,
  ADD COLUMN IF NOT EXISTS pintura_qualidade text,
  ADD COLUMN IF NOT EXISTS esquadrias_qualidade text,
  ADD COLUMN IF NOT EXISTS telhado_qualidade text,
  ADD COLUMN IF NOT EXISTS eletrica_qualidade text,
  ADD COLUMN IF NOT EXISTS habite_se boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS financiavel boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS sem_pendencias boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS liquidez_mercado text,
  ADD COLUMN IF NOT EXISTS score_diferenciais numeric,
  ADD COLUMN IF NOT EXISTS modo_avaliacao text DEFAULT 'simples';