INSERT INTO public.valuation_price_table (estado, cidade, bairro, tipo, preco_m2, notes) VALUES
-- Espírito Santo - capitais e principais cidades (preço médio por m²)
-- Vitória
('ES', 'Vitória', NULL, 'Casa', 8500, 'Média geral capital'),
('ES', 'Vitória', NULL, 'Apartamento', 9500, 'Média geral capital'),
('ES', 'Vitória', NULL, 'Terreno', 3200, 'Média geral capital'),
('ES', 'Vitória', NULL, 'Comercial', 11000, 'Média geral capital'),
('ES', 'Vitória', NULL, 'Rural', 180, 'Média geral capital'),
('ES', 'Vitória', 'Praia do Canto', 'Apartamento', 14000, 'Bairro nobre'),
('ES', 'Vitória', 'Jardim Camburi', 'Apartamento', 8500, NULL),
('ES', 'Vitória', 'Mata da Praia', 'Apartamento', 12000, NULL),
('ES', 'Vitória', 'Enseada do Suá', 'Apartamento', 13500, 'Bairro nobre'),
('ES', 'Vitória', 'Bento Ferreira', 'Apartamento', 8000, NULL),
('ES', 'Vitória', 'Jardim da Penha', 'Apartamento', 9500, NULL),
-- Vila Velha
('ES', 'Vila Velha', NULL, 'Casa', 6500, NULL),
('ES', 'Vila Velha', NULL, 'Apartamento', 7800, NULL),
('ES', 'Vila Velha', NULL, 'Terreno', 2500, NULL),
('ES', 'Vila Velha', NULL, 'Comercial', 8500, NULL),
('ES', 'Vila Velha', NULL, 'Rural', 150, NULL),
('ES', 'Vila Velha', 'Praia da Costa', 'Apartamento', 11000, 'Bairro nobre'),
('ES', 'Vila Velha', 'Itaparica', 'Apartamento', 8500, NULL),
('ES', 'Vila Velha', 'Itapuã', 'Apartamento', 9200, NULL),
('ES', 'Vila Velha', 'Coqueiral de Itaparica', 'Apartamento', 7000, NULL),
('ES', 'Vila Velha', 'Praia de Itaparica', 'Apartamento', 9800, NULL),
-- Serra
('ES', 'Serra', NULL, 'Casa', 4500, NULL),
('ES', 'Serra', NULL, 'Apartamento', 5500, NULL),
('ES', 'Serra', NULL, 'Terreno', 1800, NULL),
('ES', 'Serra', NULL, 'Comercial', 6500, NULL),
('ES', 'Serra', NULL, 'Rural', 120, NULL),
('ES', 'Serra', 'Laranjeiras', 'Apartamento', 6200, NULL),
('ES', 'Serra', 'Jardim Limoeiro', 'Apartamento', 5000, NULL),
('ES', 'Serra', 'Manguinhos', 'Casa', 5800, 'Praia'),
-- Cariacica
('ES', 'Cariacica', NULL, 'Casa', 3800, NULL),
('ES', 'Cariacica', NULL, 'Apartamento', 4500, NULL),
('ES', 'Cariacica', NULL, 'Terreno', 1500, NULL),
('ES', 'Cariacica', NULL, 'Comercial', 5500, NULL),
('ES', 'Cariacica', NULL, 'Rural', 100, NULL),
-- Guarapari
('ES', 'Guarapari', NULL, 'Casa', 5500, 'Cidade litorânea'),
('ES', 'Guarapari', NULL, 'Apartamento', 7500, 'Cidade litorânea'),
('ES', 'Guarapari', NULL, 'Terreno', 2200, NULL),
('ES', 'Guarapari', NULL, 'Comercial', 7000, NULL),
('ES', 'Guarapari', NULL, 'Rural', 130, NULL),
('ES', 'Guarapari', 'Praia do Morro', 'Apartamento', 9500, 'Praia principal'),
('ES', 'Guarapari', 'Centro', 'Apartamento', 7000, NULL),
-- Linhares
('ES', 'Linhares', NULL, 'Casa', 4200, NULL),
('ES', 'Linhares', NULL, 'Apartamento', 5000, NULL),
('ES', 'Linhares', NULL, 'Terreno', 1600, NULL),
('ES', 'Linhares', NULL, 'Comercial', 5500, NULL),
('ES', 'Linhares', NULL, 'Rural', 95, NULL),
-- Cachoeiro de Itapemirim
('ES', 'Cachoeiro de Itapemirim', NULL, 'Casa', 4000, NULL),
('ES', 'Cachoeiro de Itapemirim', NULL, 'Apartamento', 4800, NULL),
('ES', 'Cachoeiro de Itapemirim', NULL, 'Terreno', 1400, NULL),
('ES', 'Cachoeiro de Itapemirim', NULL, 'Comercial', 5200, NULL),
('ES', 'Cachoeiro de Itapemirim', NULL, 'Rural', 110, NULL),
-- São Mateus
('ES', 'São Mateus', NULL, 'Casa', 3800, NULL),
('ES', 'São Mateus', NULL, 'Apartamento', 4500, NULL),
('ES', 'São Mateus', NULL, 'Terreno', 1300, NULL),
('ES', 'São Mateus', NULL, 'Comercial', 4800, NULL),
('ES', 'São Mateus', NULL, 'Rural', 90, NULL),
-- Colatina
('ES', 'Colatina', NULL, 'Casa', 4000, NULL),
('ES', 'Colatina', NULL, 'Apartamento', 4800, NULL),
('ES', 'Colatina', NULL, 'Terreno', 1400, NULL),
('ES', 'Colatina', NULL, 'Comercial', 5000, NULL),
('ES', 'Colatina', NULL, 'Rural', 100, NULL),
-- Aracruz
('ES', 'Aracruz', NULL, 'Casa', 4500, NULL),
('ES', 'Aracruz', NULL, 'Apartamento', 5500, NULL),
('ES', 'Aracruz', NULL, 'Terreno', 1700, NULL),
('ES', 'Aracruz', NULL, 'Comercial', 6000, NULL),
('ES', 'Aracruz', NULL, 'Rural', 110, NULL),
-- Anchieta
('ES', 'Anchieta', NULL, 'Casa', 4800, 'Litoral'),
('ES', 'Anchieta', NULL, 'Apartamento', 6000, 'Litoral'),
('ES', 'Anchieta', NULL, 'Terreno', 1900, NULL),
('ES', 'Anchieta', NULL, 'Comercial', 5800, NULL),
('ES', 'Anchieta', NULL, 'Rural', 105, NULL),
-- Médias estaduais (fallback quando não tem cidade específica)
('ES', NULL, NULL, 'Casa', 5000, 'Média estadual'),
('ES', NULL, NULL, 'Apartamento', 6500, 'Média estadual'),
('ES', NULL, NULL, 'Terreno', 2000, 'Média estadual'),
('ES', NULL, NULL, 'Comercial', 7000, 'Média estadual'),
('ES', NULL, NULL, 'Rural', 120, 'Média estadual'),
-- Outros estados - médias gerais para fallback
('SP', NULL, NULL, 'Casa', 7500, 'Média estadual'),
('SP', NULL, NULL, 'Apartamento', 9500, 'Média estadual'),
('SP', NULL, NULL, 'Terreno', 3000, 'Média estadual'),
('SP', NULL, NULL, 'Comercial', 10000, 'Média estadual'),
('SP', NULL, NULL, 'Rural', 200, 'Média estadual'),
('RJ', NULL, NULL, 'Casa', 7000, 'Média estadual'),
('RJ', NULL, NULL, 'Apartamento', 9000, 'Média estadual'),
('RJ', NULL, NULL, 'Terreno', 2800, 'Média estadual'),
('RJ', NULL, NULL, 'Comercial', 9500, 'Média estadual'),
('RJ', NULL, NULL, 'Rural', 180, 'Média estadual'),
('MG', NULL, NULL, 'Casa', 5500, 'Média estadual'),
('MG', NULL, NULL, 'Apartamento', 6800, 'Média estadual'),
('MG', NULL, NULL, 'Terreno', 2200, 'Média estadual'),
('MG', NULL, NULL, 'Comercial', 7500, 'Média estadual'),
('MG', NULL, NULL, 'Rural', 140, 'Média estadual'),
('BA', NULL, NULL, 'Casa', 4500, 'Média estadual'),
('BA', NULL, NULL, 'Apartamento', 5800, 'Média estadual'),
('BA', NULL, NULL, 'Terreno', 1800, 'Média estadual'),
('BA', NULL, NULL, 'Comercial', 6200, 'Média estadual'),
('BA', NULL, NULL, 'Rural', 110, 'Média estadual')
ON CONFLICT (estado, COALESCE(cidade, ''::text), COALESCE(bairro, ''::text), tipo) DO NOTHING;