ALTER TABLE public.property_valuations
  ADD COLUMN IF NOT EXISTS numero text,
  ADD COLUMN IF NOT EXISTS tipo_estrutura text,
  ADD COLUMN IF NOT EXISTS area_terreno numeric,
  ADD COLUMN IF NOT EXISTS area_construida_terreo numeric,
  ADD COLUMN IF NOT EXISTS area_construida_superior numeric,
  ADD COLUMN IF NOT EXISTS salas integer,
  ADD COLUMN IF NOT EXISTS cozinhas integer,
  ADD COLUMN IF NOT EXISTS escritorios integer,
  ADD COLUMN IF NOT EXISTS aluguel_estimado numeric,
  ADD COLUMN IF NOT EXISTS score_localizacao numeric,
  ADD COLUMN IF NOT EXISTS score_estrutura numeric,
  ADD COLUMN IF NOT EXISTS score_acabamento numeric,
  ADD COLUMN IF NOT EXISTS score_liquidez numeric,
  ADD COLUMN IF NOT EXISTS score_documentacao numeric,
  ADD COLUMN IF NOT EXISTS score_geral numeric,
  ADD COLUMN IF NOT EXISTS pontos_fortes jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS pontos_atencao jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS sugestoes_valorizacao jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS comparaveis jsonb DEFAULT '[]'::jsonb;